### ISSUE TITLE
[TiempoReal] Ajustar la hora en las diferentes estaciones del año

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#10]
No hay mucho más que añadir al respecto; estaría muy bien que los días en el servidor se ajustaran con la posición del sol en la vida real. Por ahora los días solo coinciden cuando es invierno, y en verano (debido a que los días son más largos y al cambio de hora) a las 20:00 ya es de noche en Minecraft. Estaría bien ajustar esto en las diferentes estaciones del año.

**Comment by MiguelDreamer** [comment]
Bajarle la prioridad a este asunto, ya que se acerca el invierno otra vez y no hay urgencia por ajustar la hora en las diferentes estaciones del año hasta que vuelva a hacer falta en unos 5 meses aproximadamente.

**Comment by AlexTMjugador** [comment]
@MiguelDreamer, sería un puntazo que colocases en el tablero del proyecto de plugins de GitHub los ítems a realizar por orden, de tal forma que el primero sea más prioritario y el último el menos. 👍
