### ISSUE TITLE
Plugin multimundo para el servidor

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#12]
La isla de Khron será donde vivan los jugadores, tengan sus casas, empresas, etc y puedan utilizar las diversas funciones y servicios que el servidor otorgará. Pero, dado que el mapa principal su función no será para explorarlo para obtener recursos o jugar Minecraft con el clásico modo de supervivencia, nace la necesidad de tener un plugin multimundo.

Con este plugin, la idea es que haya diferentes mundos en el servidor, cada uno con un fin determinado. Para la versión inicial, estarán los siguientes mundos:

**- Spawn**: donde aparecen los jugadores por primera vez. Su propósito, en la primera versión, se limitará a la primera reaparición de los jugadores. Los jugadores no pueden acceder directamente a este mapa.
**- Khron**: el principal mapa del servidor donde los jugadores pueden comprar, vender, tener solares, apartamentos, participar en decisiones importantes y mucho más.
**- Supervivencia**: la experiencia clásica de Minecraft (incluyendo los mundos del Nether y el End). Los jugadores pueden acceder al mapa de Supervivencia desde el aeropuerto de Khron.

Habrá un **coste de 1 esmeralda** por usar un avión del aeropuerto de Khron para viajar a otro mundo (**100 khrones** en caso de que esté la economía de Khron implementada).

El plugin debería de ser capaz de generar mundos (no es necesario que haya una función para crear mundos directamente desde el plugin, con importar los que ya se han creado previamente y que el plugin sea capaz de seguir generando chunks, es suficiente).

Para la teletransportación entre mundos, recomendaría lo que más fácil fuese de implementar por ahora (para que las principales funciones básicas del plugin estén cuánto antes). Por portales, por comandos... lo que el desarrollador vea más oportuno.

**Comment by AlexTMjugador** [comment]
Me parece una buena idea lo propuesto. Sin embargo, como ya recuerdo haber dicho por Discord, es posible que ya haya plugins públicos que implementen lo mencionado de alguna manera. @MiguelDreamer, ¿buscaste plugins ya hechos que pudiesen valer? ¿Hay algún motivo por el que no sean aplicables a Khron?

**Comment by MiguelDreamer** [comment]
Idea descartada, el plugin Multiverse-Core funciona sin problemas en la 1.13 y no hace falta crear otro desde cero.

**Comment by MiguelDreamer** [comment]
Vuelvo a abrir la incidencia, ya que las cosas han cambiado mucho en estos últimos meses hasta ahora. Hace más de 1 mes que salió la versión 1.14 de Minecraft, y el plugin multimundo que el servidor usa actualmente (Multiverse-Core, junto con Multiverse-Portals y Multiverse-NetherPortals) da algunos problemas. He estado mirando si los desarrolladores de estos plugins han comentado algo sobre el desarrollo, futuras actualizaciones o si van a seguir dandole soporte, pero el silencio es lo único que he podido obtener. Pondré un poco de contexto:

Desde febrero de 2019, Khron ha visto aumentada su actividad e interés de los usuarios como nunca antes porque los jugadores pedían y querian jugar en un mundo de supervivencia. La situación era estable, hasta que Mojang lanzó oficialmente la 1.14. Esta versión contiene muchos cambios en la API (y tampoco ayuda que vaya peor en rendimiento), por lo que muchos de los plugins dejaron de funcionar (por cosas leves que ya han sido arregladas, ya sea por actualizaciones de los desarrolladores de sus respectivos plugins o @AlexTMjugador modificando algunos aspectos para Khron para asegurar su funcionamiento).

Sin embargo, como he comentado en el primer párrafo, el soporte a Multiverse-Core parece ser escaso o nulo desde los últimos meses, e incluso años. En la situación actual, no tener un plugin multimundo afecta gravemente a Khron porque es uno de los principales intereses de los jugadores, y desde el lanzamiento de la 1.14, el 23 de abril, ha pasado ya bastante tiempo (el servidor no está todavía oficialmente en la versión 1.14.X, pero es de esperar que esto cambie dentro de poco), y mi principal temor es que esta situación se quede en el limbo por un tiempo, presumiblemente, indeterminado.

He estado probando otro plugin, llamado LobbyAPI, que puede hacer el trabajo, pero que no recomiendo para Khron. ¿Por qué? El plugin tiene un comando que abre una interfaz con todos los mundos que se han vinculado, y al seleccionar uno de ellos, teletransporta al jugador. Pero este comando se puede ejecutar desde cualquier parte del mundo. Es decir, el aeropuerto, los puntos de spawn y todo en lo que se ha estado trabajando estos últimos meses (aspectos importantes en la jugabilidad de Khron) carecerían de sentido. Por lo que finalmente, he decidido reabrir la incidencia para que se haga un plugin multimundo para Khron.

Este plugin debería de hacer casi lo mismo que comenté al abrir la incidencia. Para no alargar más el comentario, modificaré el primer mensaje con los cambios necesarios.

**Comment by AlexTMjugador** [comment]
Si el único motivo por el que no usar LobbyAPI es que no permite restringir los lugares donde se permite usar el comando, puede simplificarse mucho el desarrollo si lo único que hacemos es un plugin que cancele la ejecución de comandos de LobbyAPI si el jugador no está en algún sitio deseado.

**Comment by AlexTMjugador** [comment]
Tengo entendido que Multiverse ya funciona sin problemas en la 1.14.3. Si es así, podemos cerrar esta incidencia. ¿Cómo lo ves, @MiguelDreamer?

**Comment by MiguelDreamer** [comment]
Me parece bien, pero creo que hay una alta probabilidad de que esta situación se vuelva a repetir en las próximas actualizaciones de Minecraft (ej: sacan la 1.15, los desarrolladores tardan casi 2 meses en actualizar el plugin). No es urgente ahora esta incidencia porque todo ha vuelto a la normalidad, pero tampoco nos podemos relajar y debemos de tener en cuenta lo que ha pasado. Como desarrollador de plugins que eres, me parece mejor que tú tomes la decisión final.

**Comment by AlexTMjugador** [comment]
Concuerdo contigo en que es posible que la situación se repita, e incluso empeore. Sin embargo, el futuro es bastante incierto, y por ahora tiene más prioridad la resolución de otras incidencias y terminación de otros proyectos.

Así pues, cierro esta incidencia de momento, pero no dudes en absoluto en volver a abrirla si esto vuelve a pasar.
