### ISSUE TITLE
[TiempoReal] Que el reloj muestre el clima actual

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#13]
Creo que sería una adición interesante para darle otra utilidad al reloj que muestre también en un mensaje el clima actual (si está soleado, hay lluvia o tormenta). Por ejemplo: "El clima es soleado/El clima es lluvioso/El clima es de tormenta". Si está lloviendo pero el jugador se encuentra en un bioma de bajas temperaturas, podría especificarse que nieva en vez de que llueva.

En las dimensiones del Nether y el End este mensaje podría omitirse, o bien poner frases como "Hace un calor infernal..." y "Hay un vacío inexplicable en este lugar", respectivamente.

**Comment by AlexTMjugador** [comment]
La idea me parece fantástica. ¿Cómo habías pensado en que se mostrase el mensaje? ¿En el chat, o en otra línea de texto de la barra de acción, donde se muestra la hora?

También se me ocurre que podría haber relojes que solo marcasen la hora, y relojes que también indicasen el tiempo atmosférico actual: unos podrían tener menos valor que otros, y generar mecánicas de comercio interesantes.

**Comment by MiguelDreamer** [comment]
Había pensado en que se mostrara en la barra de acción también (aunque si crees que otro sitio es mejor, adelante). En cuanto a los diferentes relojes, no había pensado en eso porque mi intención era que el reloj tuviese otra utilidad, no dividirlas en varios relojes (un hueco en el inventario es muy valioso, y honestamente no creo que mucha gente tenga otro reloj solo para saber si está lloviendo o no)

**Comment by AlexTMjugador** [comment]
21b64700f7e33ee2fb08844f76f2e194455abee4 facilita esto, al igual que el paquete de recursos recién implementado.

**Comment by MiguelDreamer** [comment]
Además, ahora que usamos la API de Weatherbit, también se podría mostrar la temperatura que hace en la localización del servidor en ºC.
