### ISSUE TITLE
[TiempoReal] Mostrar estadísticas sobre el tiempo activo del servidor

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#14]
Como el servidor de Khron no está abierto las 24 horas del día, para mantener una experiencia de juego equilibrada, muchas funciones se contabilizarán solo cuando el servidor esté activo. Por ello, para que el equipo de administración lo tenga más facil y para que los jugadores tengan una información clara y transparente, se me han ocurrido mejoras para el plugin de TiempoReal. Con estas mejoras, los jugadores podrán consultar información que antes no podrían saber facilmente.

Comandos para todos los jugadores (nombres de ejemplo):

/tiemposervidortotal: (muestra todas las horas en las que el servidor ha estado abierto)
/tiemposervidoractual: (muestra el tiempo que lleva el servidor encendido desde que se abrió por última vez)
/tiempoconectado: (muestra el tiempo total que ha estado el jugador conectado en el servidor desde que se unió por primera vez)
/tiempolegislatura: (muestra el tiempo desde que se empezó a contabilizar la legislatura de la democracia)
/tiemposupervivencia: (muestra el tiempo desde que el actual mapa de supervivencia está accesible para todo el mundo)

Comandos para los administradores (nombres de ejemplo):

/trempezarlegislatura: (empieza el contador sobre la legislatura)
/trempezarsupervivencia: (empieza el contador sobre el mapa de supervivencia)

Además, estaría bien que se guardara en un archivo de texto la duración (fecha y hora en la que se empezó a contar y finalizó y el tiempo total) de cada legislatura y mapa de supervivencia en el momento que se ejecute el comando que empiece a volver a contar.

**Comment by AlexTMjugador** [comment]
¡Buenas ideas! Imagino que lo de guardar esas duraciones en un fichero de texto es para tener un histórico de tiempos de legislaturas y mapas de supervivencia, ¿no?

**Comment by MiguelDreamer** [comment]
Sí, es para tener un historial, por si alguna vez nos hace falta esa información.

**Comment by AlexTMjugador** [comment]
Entonces creo que exportar esa información a un fichero CSV sería simple y suficiente. Además, un CSV puede importarse fácilmente en Excel y otras herramientas de procesado de datos, si alguna vez hiciese falta.

**Comment by MiguelDreamer** [comment]
Perfecto entonces, como te he dicho en otras incidencias, hazlo como lo creas conveniente, que yo no tengo conocimientos amplios respecto a estos temas 😄

**Comment by MiguelDreamer** [comment]
Dado que el servidor de Khron últimamente está dando más pasos hacia la creatividad (construcciones, progresos y desafíos en el mapa) y crear unas mecánicas únicas, he decidido cerrar esta propuesta. Es inútil tener en cuenta el tiempo de la legislatura y no es un dato importante para los jugadores saber cuánto tiempo ha estado activo el servidor (más bien sería una curiosidad), y creo que hay propuestas más útiles e importantes que esta en la actualidad. Si algún día se requieren estas estadísticas (u otras), volveré a abrirla.
