### ISSUE TITLE
[TiempoReal] Que el clima en determinados mapas sea igual que en la realidad

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#17]
Como la hora, estaría bien que el clima (lluvia y tormenta) sea el mismo que en la localización de servidor (Córdoba, España). Para esto es necesario tomar datos de alguna API disponible. Con esto debería de haber opciones para especificar en qué mapas esté activada esta mecánica. Una actualización cada 5 minutos para comprobar los datos sería más que suficiente.

**Comment by AlexTMjugador** [comment]
¿Te gustaría que los mundos en los que se simula el ciclo día-noche realista también tengan su tiempo meteorológico sincronizado con la realidad, o prefieres que sea un ajuste independiente, de forma que puedas tener mundos con un ciclo día-noche realista pero cuyo clima es según dicte Minecraft?

**Comment by MiguelDreamer** [comment]
Sí, esa es una idea fantástica: así, en sitios diferentes del mapa puede que esté lloviendo y en otros no, dando como resultado un clima variado en el mapa. Aunque si eso es complejo de implementar, por ahora podría ser algo básico: el mismo clima en todo el mapa.

**Comment by AlexTMjugador** [comment]
Posiblemente acabe usando el API de Weatherbit, que parece sencilla y bastante apropiada para nuestros propósitos, pues acepta coordenadas geográficas exactas: https://www.weatherbit.io/api/weather-current

**Comment by MiguelDreamer** [comment]
Actualizo aquí lo que hablamos por privado:

> Dadas las limitaciones de las API de meteorología, creemos que no es posible hacer que cada jugador vea un tiempo atmosférico diferente según donde esté. Una API, por ejemplo, admite hasta 500 llamadas por día, que equivale a una actualización cada 3 minutos (suponiendo que el servidor está encendido las 24/7). Por esto, se hará el mismo clima para todo el mundo.
