### ISSUE TITLE
[TiempoReal] Los relojes solo muestran la información al primer jugador que se lo puso en la mano

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#22]
Si un jugador se pone el reloj de bolsillo en la mano y luego otro jugador hace lo mismo, al segundo no se le muestra la información. Esto siempre ocurre y la información solo se muestra al jugador que ha cogido el reloj primero. También pasa con el reloj digital. Los relojes no hacen conflicto entre ellos (si hay alguien con el reloj de bolsillo en la mano y otro con el reloj digital, a ambos jugadores se les muestra su respectiva información).

**Comment by AlexTMjugador** [comment]
He identificado la causa del problema y estoy codificando lo que espero que sea una solución.
