### ISSUE TITLE
[TiempoReal] Temperatura y efecto de congelación

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#23]
Aquí traigo una idea con mucho potencial para ser añadida que aprovecha la mecánica de congelación de Minecraft y que creo que puede estar bastante chula.

**Temperatura y el efecto de congelación**

El jugador soporta por defecto hasta una temperatura de 10ºC (sin ningún tipo de armadura ni equipamiento). Si el jugador está en una zona con una temperatura menor, empezará a congelarse progresivamente (como cuando estás en un bloque de polvo de nieve). Un medidor interno oculto de 0 a 120 puntos aumentará propocionalmente el efecto de congelación hasta que llegue al máximo. Por ejemplo, un jugador en una zona de 9,9ºC sumará 0.1 puntos cada segundo, mientras que un jugador en una zona de 0,1ºC sumará 9.9 puntos cada segundo. Al llegar a 120 puntos, el jugador empezará a recibir daño por congelación. Se irán perdiendo puntos si el jugador vuelve a estar en una zona con una temperatura más alta. La velocidad con la que se ganan o pierden puntos depende de lo que el jugador soporte (por ejemplo, si un jugador está en una zona de 20ºC perderá 10 puntos en el medidor cada segundo).

Por lo tanto, el jugador tardará en congelarse completamente de 10 segundos a 2 minutos, duración que varía dependiendo de la temperatura del lugar.

**Armaduras**

Las armaduras y el equipamiento aumentarán la capacidad de aguante al frío del jugador.

Por orden: casco, peto, pantalones y botas, en ºC:

> Armadura de cuero: +2, +8, +6, +4 (+20ºC, el jugador no empieza a congelarse hasta que esté en una temperatura de -10ºC)
> Armadura de netherita: +1.5, +6, +4.5, +3 (+15ºC, el jugador no empieza a congelarse hasta que esté en una temperatura de -5ºC)
> Armadura de hierro, oro y diamante: +1, +4, +3, +2 (+10ºC, el jugador no empieza a congelarse hasta que esté en una temperatura de 0ºC)
> Armadura de cota de mallas: +0.5, +2, +1.5, +1 (+5ºC, el jugador no empieza a congelarse hasta que esté en una temperatura de 5ºC)
> 
> Caparazón de tortuga: +1.5
> Élitras: +2

**Fuentes de calor**

Estar en un radio de 5 bloques de una hoguera, fuego o de un horno en funcionamiento se considera una zona segura y disminuirá 4 puntos el medidor cada segundo.

**Misceláneo**

- Los jugadores en el modo creativo no se verán afectados por la mecánica de congelación.
- Un mensaje en la barra de acción que avise que el jugador está empezando a congelarse.

Es bienvenida cualquier duda, pregunta o sugerencia :)

**Comment by AlexTMjugador** [comment]
Me gusta bastante la idea de darle esta utilidad a la armadura de cuero. ¡Bien pensado!
