### ISSUE TITLE
Mostrar un texto diferente en dimensiones que no tengan hora

### ISSUE THREAD

**Issue by MiguelDreamer** [ComunidadAylas/khron-plugins#3]
Dado que el ciclo día/noche no existe en dimensiones como el Nether o en el End, estaría bien que se mostraran números aleatorios en la hora, y que la frase tuviera un color acorde con la dimensión (por ejemplo, naranja o rojo en el Nether y morado o un color oscuro en el End).

**Comment by AlexTMjugador** [comment]
Los números aleatorios en la hora bajo las condiciones mencionadas ya aparecen. Lo segundo, sin embargo, no, y sería interesante implementarlo.

**Comment by AlexTMjugador** [comment]
La confirmación anterior permite que todas las dimensiones sin un ciclo día-noche (Nether y End) muestren un texto diferente en la barra de acción. He decidido no hacer que sea diferente según de qué dimensión concreta se trate para no complicar las cosas en cuanto venga la 1.16, en la que se pueden crear dimensiones personalizadas sin un ciclo día-noche.
